type: module
name: 'Config Delete'
description: 'Delete configuration items from the UI.'
package: 'Development'
core: 8.x
core_version_requirement: ^8 || ^9

# Information added by Drupal.org packaging script on 2019-12-12
version: '8.x-1.14'
project: 'config_delete'
datestamp: 1576174084
