type: module
name: 'Config Delete'
description: 'Delete configuration items from the UI.'
package: 'Development'
core: 8.x

# Information added by Drupal.org packaging script on 2019-10-11
version: '8.x-1.09'
project: 'config_delete'
datestamp: 1570772291
